NORMAL_DATA = [
    "Net sales decreased by 5% to EUR 120.4 million.",
    "Operating profit excluding non-recurring items rose to EUR 14.5mn.",
    "The company signed a long-term agreement for the delivery of raw materials.",
    "The board proposes a dividend of EUR 0.50 per share for the fiscal year.",
    "Demand for stainless steel is expected to remain stable throughout 2026.",
    "The acquisition will strengthen our position in the Nordic market.",
    "Personnel costs were reduced through a voluntary retirement program.",
    "The new production line reached full capacity ahead of schedule.",
    "Consolidated net sales showed a slight increase year-over-year.",
    "The group's financial position remains solid with low debt levels.",
    "EBITDA increased to 12.3 million Euros in the first quarter.",
    "The investment will support the development of sustainable energy solutions.",
    "The company maintains its previous outlook for the full-year performance.",
    "The contract is valued at approximately 25 million US dollars.",
    "Sales in the construction segment were impacted by seasonal fluctuations.",
    "The CEO expressed confidence in the current strategic roadmap.",
    "Third-party logistics providers were integrated into the new supply chain.",
    "The bank's capital adequacy ratio remains well above regulatory requirements.",
    "Operating margin improved due to higher efficiency in manufacturing.",
    "The partnership aims to expand the digital service offering globally.",
    "Shareholders approved the merger during the annual general meeting.",
    "The company successfully completed a directed share issue.",
    "Revenue growth was primarily driven by the Asian market expansion.",
    "Research and development expenses were slightly higher than last year.",
    "The firm won a tender for a major infrastructure project in India."
]

SLANG_DATA = [
    "this ticker is a pure multibagger play, lfg",
    "just loaded the boat on this dip, no cap",
    "absolute diamond hands, not selling for pennies",
    "this stock is literally mid, vibes are off",
    "stop being a permabear and buy the bounce",
    "stonks only go up, everyone knows the drill 🚀",
    "this company is a total rugpull waiting to happen tbh",
    "main character energy coming from the bulls today",
    "bruh, imagine shorting this at the bottom lol",
    "pure hopium in the comments, stay safe boys",
    "the fomo is hitting hard on this breakout",
    "get rekt paper hands, the whales are buying",
    "this chart is giving me brain rot fr fr",
    "lowkey thinking about yoloing my savings into this",
    "another nothingburger earnings call from management",
    "this stonk is going to the moon or zero, no in-between",
    "market makers wildin out with these wick downs",
    "ngl this looks like a massive pump and dump",
    "short squeeze imminent, grab your popcorn",
    "rip to everyone who sold before the pump",
    "this setup is looking spicy af right now",
    "the bulls are back in town, get in or get left behind",
    "this stock is cursed, staying far away from this mess",
    "big brain play: buying the rumor and selling the news",
    "just a casual 10x potential if this holds support"
]

EXTREME_DATA = [
    "The mitochondria is the powerhouse of the cell.",
    "Neural networks are trained using gradient descent.",
    "SELECT * FROM transactions WHERE amount > 1000;",
    "def calculate_loss(y_true, y_pred): return (y_true - y_pred)**2",
    "天气很好我们今天去公园散步",
    "La economía global enfrenta desafíos estructurales.",
    "Quantum entanglement defies classical physics intuition.",
    "HTTP 500 internal server error occurred in production.",
    "The patient was diagnosed with acute respiratory distress.",
    "function add(a, b) { return a + b; }",
]