apiVersion: apps/v1
kind: Deployment
metadata:
  name: asie-inference-deployment
  namespace: asie-inference-namespace
  labels:
    app: asie-inference
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asie-inference
  template:
    metadata:
      labels:
        app: asie-inference
    spec:
      containers:
      - name: asie-inference-container
        image: asie-inference-k8s:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: asie-inference-config
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1.5"
          limits:
            memory: "3Gi"
            cpu: "3"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10