apiVersion: v1
kind: Service
metadata:
  name: asie-inference-service
  namespace: asie-inference-namespace
spec:
  type: NodePort
  selector:
    app: asie-inference
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
