apiVersion: v1
kind: Namespace
metadata:
  name: asie-inference
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
