apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PRIMARY_MODEL_PATH: "/app/exported_model/primary/model"
  PRIMARY_TOKENIZER_PATH: "/app/exported_model/primary/tokenizer"

  SHADOW_MODEL_PATH: "/app/exported_model/shadow/model"
  SHADOW_TOKENIZER_PATH: "/app/exported_model/shadow/tokenizer"

  INFERENCE_DEVICE: "cpu"
  APP_ENV: "development"
